timeout: 0
verbose: yes

/XenOS Debug
    comment: XenOS Debug Mode
    protocol: efi_chainload
    path: boot():/EFI/BOOT/winload.efi
    cmdline:/DEBUG /SOS

/XenOS
    comment: XenOS
    protocol: efi_chainload
    path: boot():/EFI/BOOT/winload.efi
    cmdline: