[package]
name = "uefi"
version = "0.36.1"
readme = "README.md"
description = """
This crate makes it easy to develop Rust software that leverages safe,
convenient, and performant abstractions for UEFI functionality.
"""
authors = ["The Rust OSDev team", "XenOS Team"]
categories = ["embedded", "no-std", "api-bindings"]
edition = "2024"
keywords = ["uefi", "efi"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AiselK/XenOS"
rust-version = "1.85.1"

# Feature documentation in uefi/lib.rs.
[features]
default = []
alloc = []
unstable = []
logger = []
global_allocator = []
panic_handler = []
qemu = ["dep:qemu-exit", "panic_handler", "log-debugcon"]
log-debugcon = []

[dependencies]
bitflags = "2.0.0"
log = { version = "0.4.5", default-features = false }
ptr_meta = { version = "0.3.0", default-features = false, features = ["derive"] }
uguid = "2.2.1"
cfg-if = "1.0.0"
ucs2 = "0.3.3"
uefi-macros = { path = "../uefi-macros" }
uefi-raw = { path = "../uefi-raw" }
qemu-exit = { version = "3.0.2", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
